networks:
  app_network:
    driver: bridge

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    env_file:
      - ./dev.env
    environment:
      - NODE_ENV=production
      - PORT=3001
    command: ["sh", "-c", "npm install --only=production && npm start"]
    stdin_open: true
    tty: true
    networks:
      - app_network

  frontend-js:
    build:
      context: ./frontend-js
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
      - PORT=3000
    stdin_open: true
    tty: true
    depends_on:
      - backend
    networks:
      - app_network

  frontend-react:
    build:
      context: ./frontend-react
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    ports:
      - "3002:80"
    environment:
      - NODE_ENV=production
      - PORT=3002
    stdin_open: true
    tty: true
    networks:
      - app_network
