version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    ports:
      - "3001:3001"
    env_file:
      - ./dev.env
    environment:
      - NODE_ENV=production
      - PORT=3001
    command: ["sh", "-c", "npm install --only=production && npm start"]
    volumes:
      - ./backend:/app
    stdin_open: true
    tty: true

  frontend:
    build:
      context: ./frontend-js
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - ./frontend-js:/app
    stdin_open: true
    tty: true
