services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    ports:
      - "3001:3001"
    env_file:
      - ./.env
    environment:
      - NODE_ENV=production
      - PORT=3001
    command: ["sh", "-c", "npm install --only=production && npm start"]
    volumes:
      - ./backend:/app
    stdin_open: true
    tty: true

  frontend-js:
    build:
      context: ./frontend-js
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - ./frontend-js:/app
    stdin_open: true
    tty: true

  frontend-react:
    build:
      context: ./frontend-react
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    ports:
      - "3002:80"
    environment:
      - NODE_ENV=production
      - PORT=3002
    volumes:
      - ./frontend-react:/app
    stdin_open: true
    tty: true
